networks:
  app-network:
    driver: bridge

volumes:
  frontend_modules:
  backend_modules:

services:
  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_modules:/app/node_modules
    networks:
      - app-network
    env_file:
      - .frontend.env
    command: ["npm", "run", "dev"]

  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
    depends_on:
      - database
    volumes:
      - ./backend:/app
      - backend_modules:/app/node_modules
    env_file:
      - .backend.env
    networks:
      - app-network
    command: ["npm", "run", "start:dev"]

  database:
    container_name: database
    restart: always
    image: mongo:latest
    volumes:
      - ./backup/data/db:/data/db
      - ./database/mongod.conf:/etc/mongod.conf
    networks:
      - app-network
    env_file:
      - .database.env
    command: --quiet --tlsMode disabled --config /etc/mongod.conf
