networks:
  app-network:
    driver: bridge

volumes:
  frontend_modules:
  backend_modules:

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_modules:/app/node_modules
    networks:
      - app-network
    restart: always
    command: ["npm", "run", "dev", "--", "--host"]

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - backend_modules:/app/node_modules
    networks:
      - app-network
    command: ["node", "backend.js"]
    restart: always
