networks:
  app-network:
    driver: bridge

volumes:
  frontend_modules:
  backend_modules:
  database_data:

services:
  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_modules:/app/node_modules
    networks:
      - app-network
    command: ["npm", "run", "dev", "--", "--host"]

  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
    depends_on:
      - database
    volumes:
      - ./backend:/app
      - backend_modules:/app/node_modules
    environment:
      - MONGO_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@database:27017/test?authSource=admin
    networks:
      - app-network
    command: ["node", "backend.js"]

  database:
    container_name: database
    restart: always
    image: mongo:latest
    volumes:
      - ./database:/app
      - database_data:/data/db
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
